on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-lastest

    steps:
    - name: 'Testing Github action'
      run: pwd 

    - name: 'printing folder contents before'
      run: ls

    - uses: actions/checkout@v3 

    - name: 'printing folder contents after'
      run: ls 
   
