on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-lastest

    steps:
    - name: 'Testing Github action'
      run: pwd 


    - uses: actions/checkout@v3 

    

    - name: "login to doker hub"
      run: doker login --username rahma117 --password dckr_pat_N72Dv-1j365GLfFXyxXfVwQix-c  
   
